!obj:pylearn2.train.Train {
    dataset: &train !obj:load_data.load_supervised {
        season: %(season)s,
        which: 'train'
    },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 90,
        layers: [
                 !obj:pylearn2.models.mlp.PretrainedLayer {
                     layer_name: 'h1',
                     layer_content: !pkl: "models/grbm_l1_%(h1)i_%(season)s.pkl"
                 },
                 !obj:pylearn2.models.mlp.PretrainedLayer {
                     layer_name: 'h2',
                     layer_content: !pkl: "models/rbm_l2_%(h1)i_%(h2)i_%(season)s.pkl"
                 },
                !obj:pylearn2.models.mlp.PretrainedLayer {
                     layer_name: 'h3',
                    layer_content: !pkl: "models/rbm_l3_%(h2)i_%(h3)i_%(season)s.pkl"
                 },
                 !obj:pylearn2.models.mlp.LinearGaussian {   ## this will be changed to an SVR 
                     init_bias: !obj:pylearn2.models.mlp.mean_of_targets {
                       dataset: *train },
                     init_beta: !obj:pylearn2.models.mlp.beta_from_targets {
                       dataset: *train },
                     min_beta: 1.,
                     max_beta: 50.,
                     beta_lr_scale: 1.,
                     dim: 1,
                     # max_col_norm: 1.9365,
                     layer_name: 'y',
                     irange: .005
                 }
                ],
        nvis: 8835 
    },
       algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
                learning_rate: 0.005,
                batch_size: 90,
                monitoring_batches: 10,
                train_iteration_mode: even_shuffled_sequential,
                monitor_iteration_mode: even_shuffled_sequential,
                monitoring_dataset : {
                        'train' : *train,
                        'test' : !obj:load_data.load_supervised {
                            season: %(season)s,
                            which: 'test'
                         },
                },
                termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
                          max_epochs: 1000,
                },
                cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
                         input_include_probs: { 'h1' : 0.8, 'h2': 0.50, 'h3': 0.50},
                         #input_scales: { 'h0': 1. }
                },
        },
    extensions: [

            # This callback makes the momentum grow to 0.9 linearly. It starts
            # growing at epoch 5 and finishes growing at epoch 6.
            # !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
             #   final_momentum: .9,
             #   start: 5,
             #   saturate: 6
           # },
    ],
    save_path: "/scratch/vandal.t/DBN_D_%(season)s.pkl",
    save_freq: 100
}
